import { jsPDF } from "jspdf";
import { Document, Packer, Paragraph, TextRun, HeadingLevel } from "docx";
import { saveAs } from "file-saver";

// Convert markdown-ish content to plain text paragraphs
function parseContent(content: string): { type: "heading" | "paragraph"; text: string; level?: number }[] {
  const lines = content.split("\n");
  const result: { type: "heading" | "paragraph"; text: string; level?: number }[] = [];

  for (const line of lines) {
    const trimmed = line.trim();
    if (!trimmed) continue;

    if (trimmed.startsWith("# ")) {
      result.push({ type: "heading", text: trimmed.slice(2), level: 1 });
    } else if (trimmed.startsWith("## ")) {
      result.push({ type: "heading", text: trimmed.slice(3), level: 2 });
    } else if (trimmed.startsWith("### ")) {
      result.push({ type: "heading", text: trimmed.slice(4), level: 3 });
    } else {
      result.push({ type: "paragraph", text: trimmed });
    }
  }

  return result;
}

export async function exportToPDF(
  content: string,
  policyType: string,
  businessName: string
): Promise<void> {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 20;
  const maxWidth = pageWidth - margin * 2;
  let yPosition = margin;
  const lineHeight = 7;

  // Title
  doc.setFontSize(20);
  doc.setFont("helvetica", "bold");
  doc.text(`${policyType}`, pageWidth / 2, yPosition, { align: "center" });
  yPosition += 10;

  doc.setFontSize(12);
  doc.setFont("helvetica", "normal");
  doc.text(`${businessName}`, pageWidth / 2, yPosition, { align: "center" });
  yPosition += 15;

  // Parse and render content
  const parsed = parseContent(content);

  for (const item of parsed) {
    // Check for page break
    if (yPosition > doc.internal.pageSize.getHeight() - margin) {
      doc.addPage();
      yPosition = margin;
    }

    if (item.type === "heading") {
      yPosition += 5;
      const fontSize = item.level === 1 ? 16 : item.level === 2 ? 14 : 12;
      doc.setFontSize(fontSize);
      doc.setFont("helvetica", "bold");

      const lines = doc.splitTextToSize(item.text, maxWidth);
      doc.text(lines, margin, yPosition);
      yPosition += lines.length * lineHeight + 3;
    } else {
      doc.setFontSize(10);
      doc.setFont("helvetica", "normal");

      const lines = doc.splitTextToSize(item.text, maxWidth);

      for (const line of lines) {
        if (yPosition > doc.internal.pageSize.getHeight() - margin) {
          doc.addPage();
          yPosition = margin;
        }
        doc.text(line, margin, yPosition);
        yPosition += lineHeight;
      }
      yPosition += 2;
    }
  }

  // Footer
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setFont("helvetica", "normal");
    doc.text(
      `Generated by PolicyPal - Page ${i} of ${pageCount}`,
      pageWidth / 2,
      doc.internal.pageSize.getHeight() - 10,
      { align: "center" }
    );
  }

  doc.save(`${policyType.toLowerCase().replace(/\s+/g, "-")}-${businessName.toLowerCase().replace(/\s+/g, "-")}.pdf`);
}

export async function exportToWord(
  content: string,
  policyType: string,
  businessName: string
): Promise<void> {
  const parsed = parseContent(content);

  const children: Paragraph[] = [
    // Title
    new Paragraph({
      text: policyType,
      heading: HeadingLevel.TITLE,
      spacing: { after: 200 },
    }),
    new Paragraph({
      text: businessName,
      spacing: { after: 400 },
    }),
  ];

  for (const item of parsed) {
    if (item.type === "heading") {
      const level = item.level === 1
        ? HeadingLevel.HEADING_1
        : item.level === 2
          ? HeadingLevel.HEADING_2
          : HeadingLevel.HEADING_3;

      children.push(
        new Paragraph({
          text: item.text,
          heading: level,
          spacing: { before: 240, after: 120 },
        })
      );
    } else {
      children.push(
        new Paragraph({
          children: [new TextRun(item.text)],
          spacing: { after: 120 },
        })
      );
    }
  }

  // Footer
  children.push(
    new Paragraph({
      children: [
        new TextRun({
          text: `Generated by PolicyPal on ${new Date().toLocaleDateString()}`,
          size: 18,
          italics: true,
        }),
      ],
      spacing: { before: 400 },
    })
  );

  const doc = new Document({
    sections: [{ properties: {}, children }],
  });

  const blob = await Packer.toBlob(doc);
  saveAs(blob, `${policyType.toLowerCase().replace(/\s+/g, "-")}-${businessName.toLowerCase().replace(/\s+/g, "-")}.docx`);
}

export function exportToHTML(
  content: string,
  policyType: string,
  businessName: string
): void {
  const parsed = parseContent(content);

  let html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${policyType} - ${businessName}</title>
  <style>
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, sans-serif;
      line-height: 1.6;
      max-width: 800px;
      margin: 0 auto;
      padding: 40px 20px;
      color: #333;
    }
    h1 { font-size: 2em; margin-bottom: 0.5em; }
    h2 { font-size: 1.5em; margin-top: 1.5em; margin-bottom: 0.5em; }
    h3 { font-size: 1.25em; margin-top: 1.25em; margin-bottom: 0.5em; }
    p { margin-bottom: 1em; }
    .business-name { color: #666; margin-bottom: 2em; }
    .footer { margin-top: 3em; font-size: 0.85em; color: #999; border-top: 1px solid #eee; padding-top: 1em; }
  </style>
</head>
<body>
  <h1>${policyType}</h1>
  <p class="business-name">${businessName}</p>
`;

  for (const item of parsed) {
    if (item.type === "heading") {
      const tag = `h${Math.min(item.level || 1, 3) + 1}`;
      html += `  <${tag}>${escapeHtml(item.text)}</${tag}>\n`;
    } else {
      html += `  <p>${escapeHtml(item.text)}</p>\n`;
    }
  }

  html += `  <div class="footer">Generated by PolicyPal on ${new Date().toLocaleDateString()}</div>
</body>
</html>`;

  const blob = new Blob([html], { type: "text/html;charset=utf-8" });
  saveAs(blob, `${policyType.toLowerCase().replace(/\s+/g, "-")}-${businessName.toLowerCase().replace(/\s+/g, "-")}.html`);
}

function escapeHtml(text: string): string {
  return text
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#039;");
}

export function copyToClipboard(content: string): Promise<void> {
  return navigator.clipboard.writeText(content);
}
